Bubble Sort Ruby Program using yield
Abhigyan001/bubble_sort pull request #1
Opened 2020-09-17 14:55 UTC by Abhigyan001

- Created a bubble sort program in ruby. The first method is created using "while" loop and the elements are iterated inside it to sort the elements in increasing order.

- After the loop is over, the array is sorted and can be viewed using print or puts.

- The second method uses the same logic, For comparison, we used "yeild" and ".negative?"  to determine the appropriate course of action.

- The array accepts strings as well as numbers as arguments and implements bubble sort to sort them.

2020-09-17 19:23 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General
- [ ]  Let's use a more concise title for this project in your read.MD file, for example  `Bubble Sort`.
- [ ] You should use an imperative form for commits instead of  past tense(For feature projects)
- [ ] You should use Github flow not Gitflow  ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_bubble_sort/git.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/57421588/))
- [ ] Check comments below
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-09-17 19:23 UTC, kobiyoyo commented on bubblesort.rb
> +end
Let's remove this debug code.

2020-09-17 19:23 UTC, kobiyoyo commented on bubblesort.rb
> +  puts my_arr
Ruby methods automatically returns the last evaluated statement therefore, there is no need for `puts`. Let's remove it

2020-09-18 06:28 UTC, voscarmv approved these changes
# Status: Project Approved ✨ 😎👍 💯 ✔️
### You may merge this branch and move forward ⛙🛣

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-09-18 07:29 UTC, merged